spring.application.name=unipdi

server.port=8080

#MongoDB Connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/unipdi}
#spring.data.mongodb.uri=spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/unipdi}
#spring.data.mongodb.uri=spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/unipdi?authSource=admin}
